cores = {'valor1':'\033[4;31m', 'valor2':'\033[4;33m', 'limpa':'\033[m'}
a = input('Digite algo: ')
print('O tipo primitivo desse valor é', cores['valor1'], type(a), cores['limpa'])
print('Só tem espaços? ', cores['valor2'], a.isspace(), cores['limpa'])
print('É um número? ', cores['valor1'], a.isnumeric(), cores['limpa'])
print('É alfabético? ', cores['valor2'], a.isalpha(), cores['limpa'])
print('É alfanumérico? ', cores['valor1'], a.isalnum(), cores['limpa'])
print('Está em maiúculas? ', cores['valor2'], a.isupper(), cores['limpa'])
print('Está em minúsculas?', cores['valor1'], a.islower(), cores['limpa'])
print('Está capitalizada? ', cores['valor2'], a.istitle(), cores['limpa'])